/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package helpdesk;

import java.sql.Connection;
import java.sql.PreparedStatement;
import javax.swing.JOptionPane;

/**
 *
 * @author ravindu
 */
public class NewUserPnl extends javax.swing.JFrame {

    /**
     * Creates new form NewUserPnl
     */
    public NewUserPnl() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        Usr_EPF_Input = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        Usr_Name_Input = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        Usr_Desig_Input = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        Usr_Division_Input = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        Usr_Fault_Input = new javax.swing.JTextArea();
        btnUserSubmit = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        CEA_Input_Usr = new javax.swing.JTextField();
        Item_Type_Input_Usr = new javax.swing.JTextField();
        Brand_Input_Usr = new javax.swing.JTextField();
        Device_Type_Input_Usr = new javax.swing.JTextField();
        Year_Input_Usr = new javax.swing.JTextField();
        Division_Input_Usr = new javax.swing.JTextField();
        Number_Input_Usr = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(204, 204, 255));

        jLabel1.setText("EPF No");

        Usr_EPF_Input.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Usr_EPF_InputActionPerformed(evt);
            }
        });

        jLabel2.setText("Name");

        jLabel3.setText("Designation");

        jLabel4.setText("Division");

        jLabel5.setText("Fault");

        Usr_Fault_Input.setColumns(20);
        Usr_Fault_Input.setRows(5);
        jScrollPane2.setViewportView(Usr_Fault_Input);

        btnUserSubmit.setBackground(new java.awt.Color(153, 153, 255));
        btnUserSubmit.setText("Submit");
        btnUserSubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUserSubmitActionPerformed(evt);
            }
        });

        jLabel6.setText("CEA No");

        CEA_Input_Usr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CEA_Input_UsrActionPerformed(evt);
            }
        });

        Item_Type_Input_Usr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Item_Type_Input_UsrActionPerformed(evt);
            }
        });

        Brand_Input_Usr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Brand_Input_UsrActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5))
                        .addGap(60, 60, 60)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Usr_Name_Input, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Usr_EPF_Input, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Usr_Desig_Input, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Usr_Division_Input, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(CEA_Input_Usr, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Item_Type_Input_Usr, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Brand_Input_Usr, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Device_Type_Input_Usr, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Year_Input_Usr, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Division_Input_Usr, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Number_Input_Usr, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 325, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnUserSubmit))))
                .addContainerGap(267, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(Usr_EPF_Input, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(Usr_Name_Input, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(Usr_Desig_Input, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(Usr_Division_Input, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(CEA_Input_Usr, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Item_Type_Input_Usr, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Brand_Input_Usr, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Device_Type_Input_Usr, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Year_Input_Usr, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Division_Input_Usr, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Number_Input_Usr, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(63, 63, 63)
                        .addComponent(jLabel5)))
                .addGap(51, 51, 51)
                .addComponent(btnUserSubmit)
                .addContainerGap(382, Short.MAX_VALUE))
        );

        jScrollPane1.setViewportView(jPanel1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Usr_EPF_InputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Usr_EPF_InputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Usr_EPF_InputActionPerformed

    private void CEA_Input_UsrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CEA_Input_UsrActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CEA_Input_UsrActionPerformed

    private void Item_Type_Input_UsrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Item_Type_Input_UsrActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Item_Type_Input_UsrActionPerformed

    private void Brand_Input_UsrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Brand_Input_UsrActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Brand_Input_UsrActionPerformed

    private void btnUserSubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUserSubmitActionPerformed
        // TODO add your handling code here:
        
        try{
        
            Connection cn=MySQLConnect.ConnectDB();
            String sql="insert into all_table(EPF_No,Name,Designation,Division,Fault,CEA_No,Item_Type,Brand,Device_Type,Year,CEA_division,Num) values(?,?,?,?,?,?,?,?,?,?,?,?)";
           // ps=cn.prepareStatement(sql);
           //String sql="UPDATE all_table SET EPF_No=?,Name=?,Designation=?,Division=?,Fault=?,CEA_No=?,Item_Type=?,Brand=?,Device_Type=?,Year=?,CEA_division=?,Num=?"+value;
           
           final PreparedStatement ps= cn.prepareStatement(sql);
            ps.setString(1,Usr_EPF_Input.getText());
            ps.setString(2,Usr_Name_Input.getText());
            ps.setString(3,Usr_Desig_Input.getText());
            ps.setString(4,Usr_Division_Input.getText());
            ps.setString(5,Usr_Fault_Input.getText());
            ps.setString(6,CEA_Input_Usr.getText());
            ps.setString(7,Item_Type_Input_Usr.getText());
            ps.setString(8,Brand_Input_Usr.getText());
            ps.setString(9,Device_Type_Input_Usr.getText());
            ps.setString(10,Year_Input_Usr.getText());
            ps.setString(11,Division_Input_Usr.getText());
            ps.setString(12,Number_Input_Usr.getText());
            ps.execute();
            
   
         /*
            //CEA Inputs :-
            String sq="insert into cea(CEA_No,Item_Type,Brand,Device_Type,Year,Division,Num) values(?,?,?,?,?,?,?)";
            final PreparedStatement prs= cn.prepareStatement(sq);
            prs.setString(1,CEA_Input_Usr.getText());
            prs.setString(2,Item_Type_Input_Usr.getText());
            prs.setString(3,Brand_Input_Usr.getText());
            prs.setString(4,Device_Type_Input_Usr.getText());
            prs.setString(5,Year_Input_Usr.getText());
            prs.setString(6,Division_Input_Usr.getText());
            prs.setString(7,Number_Input_Usr.getText());
            prs.execute();  */
            JOptionPane.showMessageDialog(this,"Successfully added");
            
            Usr_EPF_Input.setText("");
            Usr_Name_Input.setText("");
            Usr_Desig_Input.setText("");
            Usr_Division_Input.setText("");
            Usr_Fault_Input.setText("");
                 
            CEA_Input_Usr.setText("");
            Item_Type_Input_Usr.setText("");
            Brand_Input_Usr.setText("");
            Device_Type_Input_Usr.setText("");
            Year_Input_Usr.setText("");
            Division_Input_Usr.setText("");
            Number_Input_Usr.setText("");
            
            
        }catch(Exception e){
            JOptionPane.showMessageDialog(this, e);
        }
    }//GEN-LAST:event_btnUserSubmitActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewUserPnl.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewUserPnl.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewUserPnl.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewUserPnl.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewUserPnl().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Brand_Input_Usr;
    private javax.swing.JTextField CEA_Input_Usr;
    private javax.swing.JTextField Device_Type_Input_Usr;
    private javax.swing.JTextField Division_Input_Usr;
    private javax.swing.JTextField Item_Type_Input_Usr;
    private javax.swing.JTextField Number_Input_Usr;
    private javax.swing.JTextField Usr_Desig_Input;
    private javax.swing.JTextField Usr_Division_Input;
    private javax.swing.JTextField Usr_EPF_Input;
    private javax.swing.JTextArea Usr_Fault_Input;
    private javax.swing.JTextField Usr_Name_Input;
    private javax.swing.JTextField Year_Input_Usr;
    private javax.swing.JButton btnUserSubmit;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables
}
